disks:
  - name: wormgpt-data
    mountPath: /data
    sizeGB: 1

services:
  # Frontend static site
  - type: static
    name: wormgpt-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wormgpt-api.onrender.com

  # Telegram Bot Service
  - type: web
    name: wormgpt-keygen
    disk:
      name: wormgpt-data
      mountPath: /data
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r keygen_requirements.txt
      mkdir -p /data
    startCommand: python KEYGEN.PY
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BOT_TOKEN
        value: "7787758054:AAGYh_NE_3pWp5VgQggbHS0U2VaVu-ZzPuU"
      - key: CHANNEL_USERNAME
        value: "hecabruss"
      - key: CHANNEL_LINK
        value: "https://t.me/hecabruss"
      - key: USER_DATA_FILE
        value: /data/user_data.json
      - key: PORT
        value: 8080

  # Backend API
  - type: web
    name: wormgpt-api
    disk:
      name: wormgpt-data
      mountPath: /data
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /data
      cp ./user_data.json /data/user_data.json || echo "Failed to copy user_data.json"
      chmod -R 777 /data
      ls -la /data  # Debug file presence
    startCommand: cd api && gunicorn server:app
    envVars:
      - key: USER_DATA_FILE
        value: /data/user_data.json
