disks:
  - name: wormgpt-data
    mountPath: /data
    sizeGB: 1

services:
  # Frontend static site
  - type: static
    name: wormgpt-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wormgpt-api.onrender.com

  # Backend API
  - type: web
    name: wormgpt-api
    env: python
    disk:
      name: wormgpt-data
      mountPath: /data
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /data
      cp user_data.json /data/user_data.json || echo "No initial user_data.json"
      chmod 666 /data/user_data.json || true
    startCommand: cd api && gunicorn server:app
    envVars:
      - key: USER_DATA_FILE
        value: /data/user_data.json

  # Telegram Bot Service
  - type: web
    name: wormgpt-keygen
    env: python
    disk:
      name: wormgpt-data
      mountPath: /data
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r keygen_requirements.txt
      mkdir -p /data
    startCommand: python KEYGEN.PY
    envVars:
      - key: USER_DATA_FILE
        value: /data/user_data.json
